name: Continuous Delivery

on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: projeto.zip
          path: README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: projeto.zip
      - name: Display structure of the artifact
        run: ls -R

     