name: Continuous Integration

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install ESLint
        run: npm install eslint --no-save

      - name: Run linters
        uses: wearerequired/lint-action@v3
        with:
          eslint: true
          eslint_extensions: js

  discord-webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Run Discord Webhook
        uses: johnnyhuy/actions-discord-git-webhook@main
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}